#! /bin/sh

# STARTUP
pgrep -x sxhkd > /dev/null || sxhkd &
#feh --bg-fill --randomize ~/Wallpapers/wall/nwall1.jpeg &
#feh --bg-fill ~/Wallpapers/wall/Jesus.jpg &
feh --bg-scale ~/Wallpapers/10.png &
#feh --bg-center ~/Wallpapers/wall/wallp.png --bg-center ~/Documents/Wallpapers/wall/nwall2.jpeg &
picom &
~/.config/polybar/launch.sh

# DESKTOPS
bspc wm -O DP-4 -s HDMI-0
bspc monitor DP-4 -d 1 2 3 4 5
#bspc monitor -d 1 2 3 4 5
bspc monitor HDMI-0 -d 6 7 8 9

# CONFIG
bspc config border_width		        2
bspc config window_gap		            0
#bspc config window_gap		            6
bspc config active_border_color         '#5d5d5d'
bspc config normal_border_color         '#000000'
bspc config focused_border_color        '#5d5d5d'

bspc config top_padding		            0
#bspc config top_padding		            19.5
bspc config right_padding		        0
#bspc config bottom_padding		        0
bspc config bottom_padding		        19
bspc config split_ratio                 0.5
bspc config single_monocle              true 
bspc config gapless_monocle             true
bspc config ignore_ewmh_focus           true
bspc config borderless_monocle          false 

# RULES
bspc rule -a "*:*:ffmpeg" desktop=focused state=floating 
bspc rule -a "Anki:*:Migaku Dictionary" desktop=focused
bspc rule -a "Anki:*:Migaku Card Exporter" desktop=focused 
bspc rule -a Anki --one-shot desktop=^5
bspc rule -a Google-chrome --one-shot desktop=^2 
bspc rule -a discord desktop=^6 
bspc rule -a qBittorrent desktop=^4 
bspc rule -a qutebrowser --one-shot desktop=^2
bspc rule -a Spotify:Spotify desktop=^6
bspc rule -a spotify:Spotify desktop=^6
bspc rule -a Spotify:spotify desktop=^6
bspc rule -a Thunar desktop=^4 focus=on follow=on
bspc rule -a vlc desktop=^4 --one-shot focus=on follow=on
bspc rule -a Zathura state=tiled
bspc rule -a Pentablet state=floating


#BASIC
#bspc config active_border_color         '#db1f64'
#bspc config normal_border_color         '#000000'
#bspc config focused_border_color        '#db1f64'
